/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/nivesh-star/ondc/src/server"
)

func main() {
	log.Printf("Server started")

	router := server.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
