/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

import (
	"time"
)

// The current state of fulfillment. The BPP must set this value whenever the state of the order fulfillment changes and fire an unsolicited `on_status` call.
type AllOfFulfillmentState struct {
	Descriptor Descriptor `json:"descriptor,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ID of entity which changed the state
	UpdatedBy string `json:"updated_by,omitempty"`
}
