/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type OnRatingBody struct {
	Context *AllOfonRatingBodyContext `json:"context"`

	Message *OnRatingMessage `json:"message"`

	Error_ *ModelError `json:"error,omitempty"`
}
