/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// The creator of this item
type AllOfItemCreator struct {
	Descriptor *Descriptor `json:"descriptor,omitempty"`
	// The postal address of the organization
	Address string `json:"address,omitempty"`
	// The state where the organization's address is registered
	State string `json:"state,omitempty"`
	// The city where the the organization's address is registered
	City string `json:"city,omitempty"`

	Contact Contact `json:"contact,omitempty"`
}
