/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Physical description of something.
type Descriptor struct {
	Name string `json:"name,omitempty"`

	Code string `json:"code,omitempty"`

	ShortDesc string `json:"short_desc,omitempty"`

	LongDesc string `json:"long_desc,omitempty"`

	AdditionalDesc DescriptorAdditionalDesc `json:"additional_desc,omitempty"`

	Media []MediaFile `json:"media,omitempty"`

	Images []Image `json:"images,omitempty"`
}
