/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type PaymentParams struct {
	// The reference transaction ID associated with a payment activity
	TransactionId string `json:"transaction_id,omitempty"`

	Amount string `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`

	BankCode string `json:"bank_code,omitempty"`

	BankAccountNumber string `json:"bank_account_number,omitempty"`

	VirtualPaymentAddress string `json:"virtual_payment_address,omitempty"`

	SourceBankCode string `json:"source_bank_code,omitempty"`

	SourceBankAccountNumber string `json:"source_bank_account_number,omitempty"`

	SourceVirtualPaymentAddress string `json:"source_virtual_payment_address,omitempty"`
}
