/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a form
type Form struct {
	// The URL from where the form can be fetched. The content fetched from the url must be processed as per the mime_type specified in this object. Once fetched, the rendering platform can choosed to render the form as-is as an embeddable element; or process it further to blend with the theme of the application. In case the interface is non-visual, the the render can process the form data and reproduce it as per the standard specified in the form.
	Url string `json:"url,omitempty"`
	// The form submission data
	Data map[string]string `json:"data,omitempty"`
	// This field indicates the nature and format of the form received by querying the url. MIME  package types are defined and standardized in IETF's RFC 6838.
	MimeType string `json:"mime_type,omitempty"`

	SubmissionId string `json:"submission_id,omitempty"`
}
