/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type ContentTypeEnum string

const (
	TextPlain       ContentTypeEnum = "text/plain"
	TextHtml        ContentTypeEnum = "text/html"
	ApplicationJson ContentTypeEnum = "application/json"
)

type DescriptorAdditionalDesc struct {
	Url string `json:"url,omitempty"`

	ContentType ContentTypeEnum `json:"content_type,omitempty"`
}
