/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes the return policy of an item or an order
type ReturnTerm struct {
	// The state of fulfillment during which this term IETF''s applicable.
	FulfillmentState AllOfReturnTermFulfillmentState `json:"fulfillment_state,omitempty"`
	// Indicates whether the item is eligible for return
	ReturnEligible bool `json:"return_eligible,omitempty"`
	// Applicable only for buyer managed returns where the buyer has to return the item to the origin before a certain date-time, failing which they will not be eligible for refund.
	ReturnTime AllOfReturnTermReturnTime `json:"return_time,omitempty"`
	// The location where the item or order must / will be returned to
	ReturnLocation AllOfReturnTermReturnLocation `json:"return_location,omitempty"`
	// The entity that will perform the return
	FulfillmentManagedBy string `json:"fulfillment_managed_by,omitempty"`
}
