/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Refund term of an item or an order
type ItemRefundTerms struct {
	// The state of fulfillment during which this term is applicable.
	FulfillmentState *AllOfItemRefundTermsFulfillmentState `json:"fulfillment_state,omitempty"`
	// Indicates if cancellation will result in a refund
	RefundEligible bool `json:"refund_eligible,omitempty"`
	// Time within which refund will be processed after successful cancellation.
	RefundWithin AllOfItemRefundTermsRefundWithin `json:"refund_within,omitempty"`

	RefundAmount Price `json:"refund_amount,omitempty"`
}
