/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type OnRatingMessage struct {
	// A feedback form to allow the user to provide additional information on the rating provided
	FeedbackForm *AllOfonRatingMessageFeedbackForm `json:"feedback_form,omitempty"`
}
