/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

import (
	"time"
)

// Updated order object
type AllOfupdateMessageOrder struct {
	// Human-readable ID of the order. This is generated at the BPP layer. The BPP can either generate order id within its system or forward the order ID created at the provider level.
	Id string `json:"id,omitempty"`
	// A list of order IDs to link this order to previous orders.
	RefOrderIds []string `json:"ref_order_ids,omitempty"`
	// Status of the order. Allowed values can be defined by the network policy
	Status string `json:"status,omitempty"`
	// This is used to indicate the type of order being created to BPPs. Sometimes orders can be linked to previous orders, like a replacement order in a retail domain. A follow-up consultation in healthcare domain. A single order part of a subscription order. The list of order  package types can be standardized at the network level.
	Type_ string `json:"type,omitempty"`
	// Details of the provider whose catalog items have been selected.
	Provider string `json:"provider,omitempty"`
	// The items purchased / availed in this order
	Items []Item `json:"items,omitempty"`
	// The add-ons purchased / availed in this order
	AddOns []AddOn `json:"add_ons,omitempty"`
	// The offers applied in this order
	Offers []Offer `json:"offers,omitempty"`
	// The billing details of this order
	Billing string `json:"billing,omitempty"`
	// The fulfillments involved in completing this order
	Fulfillments []Fulfillment `json:"fulfillments,omitempty"`
	// The cancellation details of this order
	Cancellation string `json:"cancellation,omitempty"`
	// Cancellation terms of this item
	CancellationTerms []CancellationTerm `json:"cancellation_terms,omitempty"`
	// Refund terms of this item TODO:
	//RefundTerms []ItempropertiesrefundTermsitems `json:"refund_terms,omitempty"`
	// Replacement terms of this item
	ReplacementTerms []ReplacementTerm `json:"replacement_terms,omitempty"`
	// Return terms of this item
	ReturnTerms []ReturnTerm `json:"return_terms,omitempty"`
	// The mutually agreed upon quotation for this order.
	Quote string `json:"quote,omitempty"`
	// The terms of settlement for this order
	Payments []Payment `json:"payments,omitempty"`
	// The date-time of creation of this order
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The date-time of updated of this order
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Additional input required from the customer to confirm this order
	Xinput string `json:"xinput,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}
