/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type AllOfOrganizationAddress string

// An organization. Usually a recognized business entity.
type Organization struct {
	Descriptor Descriptor `json:"descriptor,omitempty"`
	// The postal address of the organization
	Address AllOfOrganizationAddress `json:"address,omitempty"`
	// The state where the organization's address is registered
	State AllOfOrganizationState `json:"state,omitempty"`
	// The city where the the organization's address is registered
	City AllOfOrganizationCity `json:"city,omitempty"`

	Contact Contact      `json:"contact,omitempty"`
	Creds   []Credential `json:"creds,omitempty"`
}
