/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a credential of an entity - Person or Organization
type Credential struct {
	Id string `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`
	// URL of the credential
	Url string `json:"url,omitempty"`
}
