/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// The country this location is, or is located within
type AllOfLocationCountry struct {
	// Name of the country
	Name string `json:"name,omitempty"`
	// Country code as per ISO 3166-1 and ISO 3166-2 format
	Code string `json:"code,omitempty"`
}
