/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes the rating of an entity
type Rating struct {
	// Category of the entity being rated
	RatingCategory string `json:"rating_category,omitempty"`
	// Id of the object being rated
	Id string `json:"id,omitempty"`
	// Rating value given to the object. This can be a single value or can also contain an inequality operator like gt, gte, lt, lte. This can also contain an inequality expression containing logical operators like && and ||.
	Value string `json:"value,omitempty"`
}
