/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type CancelMessage struct {
	OrderId string `json:"order_id"`

	CancellationReasonId string `json:"cancellation_reason_id,omitempty"`

	Descriptor *Descriptor `json:"descriptor,omitempty"`
}
