/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// The mutually agreed upon quotation for this order.
type AllOfOrderQuote struct {
	// ID of the quote.
	Id string `json:"id,omitempty"`
	// The total quoted price
	Price string `json:"price,omitempty"`
	// the breakup of the total quoted price
	Breakup []QuotationBreakup `json:"breakup,omitempty"`

	Ttl string `json:"ttl,omitempty"`
}
