/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type UpdateMessage struct {
	// Comma separated values of order objects being updated. For example: ```\"update_target\":\"item,billing,fulfillment\"```
	UpdateTarget string `json:"update_target"`
	// Updated order object
	Order *AllOfupdateMessageOrder `json:"order"`
}
