/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

import (
	"time"
)

// The state of fulfillment during which this term is applicable.
type AllOfCancellationTermFulfillmentState struct {
	Descriptor Descriptor `json:"descriptor,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ID of entity which changed the state
	UpdatedBy string `json:"updated_by,omitempty"`
}
