/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// The reason for cancellation
type AllOfCancellationReason struct {
	Id string `json:"id,omitempty"`

	Descriptor *Descriptor `json:"descriptor,omitempty"`
}
