/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type InitBody struct {
	Context *AllOfinitBodyContext `json:"context"`

	Message *SelectMessage `json:"message"`
}
