/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type RatingBody struct {
	Context *AllOfratingBodyContext `json:"context"`

	Message *RatingMessage `json:"message"`
}
