/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes an additional item offered as a value-addition to a product or service. This does not exist independently in a catalog and is always associated with an item.
type AddOn struct {
	// Provider-defined ID of the add-on
	Id string `json:"id,omitempty"`

	Descriptor Descriptor `json:"descriptor,omitempty"`

	Price Price `json:"price,omitempty"`
}
