/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes the cancellation terms of an item or an order. This can be referenced at an item or order level. Item-level cancellation terms can override the terms at the order level.
type CancellationTerm struct {
	// The state of fulfillment during which this term is applicable.
	FulfillmentState AllOfCancellationTermFulfillmentState `json:"fulfillment_state,omitempty"`
	// Indicates whether a reason is required to cancel the order
	ReasonRequired bool `json:"reason_required,omitempty"`
	// Information related to the time of cancellation.
	CancelBy *AllOfCancellationTermCancelBy `json:"cancel_by,omitempty"`

	CancellationFee Fee `json:"cancellation_fee,omitempty"`

	Xinput XInput `json:"xinput,omitempty"`

	ExternalRef MediaFile `json:"external_ref,omitempty"`
}
