/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Details on how the customer wants their order fulfilled
type AllOfIntentFulfillment struct {
	// Unique reference ID to the fulfillment of an order
	Id string `json:"id,omitempty"`
	// A code that describes the mode of fulfillment. This is typically set when there are multiple ways an order can be fulfilled. For example, a retail order can be fulfilled either via store pickup or a home delivery. Similarly, a medical consultation can be provided either in-person or via tele-consultation. The network policy must publish standard fulfillment type codes for the different modes of fulfillment.
	Type_ string `json:"type,omitempty"`
	// Whether the fulfillment can be rated or not
	Rateable bool `json:"rateable,omitempty"`
	// The rating value of the fulfullment service.
	Rating string `json:"rating,omitempty"`
	// The current state of fulfillment. The BPP must set this value whenever the state of the order fulfillment changes and fire an unsolicited `on_status` call.
	State string `json:"state,omitempty"`
	// Indicates whether the fulfillment allows tracking
	Tracking bool `json:"tracking,omitempty"`
	// The person that will ultimately receive the order
	Customer string `json:"customer,omitempty"`
	// The agent that is currently handling the fulfillment of the order
	Agent Agent `json:"agent,omitempty"`

	Contact Contact `json:"contact,omitempty"`

	Vehicle Vehicle `json:"vehicle,omitempty"`
	// The list of logical stops encountered during the fulfillment of an order.
	Stops []Stop `json:"stops,omitempty"`
	// The physical path taken by the agent that can be rendered on a map. The allowed format of this property can be set by the network.
	Path string `json:"path,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}
