/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a scalar
type Scalar struct {
	Type_ string `json:"type,omitempty"`

	Value string `json:"value,omitempty"`

	EstimatedValue string `json:"estimated_value,omitempty"`

	ComputedValue string `json:"computed_value,omitempty"`

	Range_ ScalarRange `json:"range,omitempty"`

	Unit string `json:"unit,omitempty"`
}
