/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// A logical point in space and time during the fulfillment of an order.
type Stop struct {
	Id string `json:"id,omitempty"`

	ParentStopId string `json:"parent_stop_id,omitempty"`
	// Location of the stop
	Location AllOfStopLocation `json:"location,omitempty"`
	// The type of stop. Allowed values of this property can be defined by the network policy.
	Type_ string `json:"type,omitempty"`
	// Timings applicable at the stop.
	Time AllOfStopTime `json:"time,omitempty"`
	// Instructions that need to be followed at the stop
	Instructions AllOfStopInstructions `json:"instructions,omitempty"`
	// Contact details of the stop
	Contact AllOfStopContact `json:"contact,omitempty"`
	// The details of the person present at the stop
	Person AllOfStopPerson `json:"person,omitempty"`

	Authorization Authorization `json:"authorization,omitempty"`
}
