/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a vehicle is a device that is designed or used to transport people or cargo over land, water, air, or through space.<br>This has properties like category, capacity, make, model, size,variant,color,energy_type,registration
type Vehicle struct {
	Category string `json:"category,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	Make string `json:"make,omitempty"`

	Model string `json:"model,omitempty"`

	Size string `json:"size,omitempty"`

	Variant string `json:"variant,omitempty"`

	Color string `json:"color,omitempty"`

	EnergyType string `json:"energy_type,omitempty"`

	Registration string `json:"registration,omitempty"`

	WheelsCount string `json:"wheels_count,omitempty"`

	CargoVolumne string `json:"cargo_volumne,omitempty"`

	WheelchairAccess string `json:"wheelchair_access,omitempty"`

	Code string `json:"code,omitempty"`

	EmissionStandard string `json:"emission_standard,omitempty"`
}
