/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type OnUpdateBody struct {
	Context *AllOfonUpdateBodyContext `json:"context"`

	Message *SelectMessage `json:"message,omitempty"`

	Error_ *ModelError `json:"error,omitempty"`
}
