/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type AllOfFeePercentage string

// A fee applied on a particular entity
type Fee struct {
	// Percentage of a value
	Percentage AllOfFeePercentage `json:"percentage,omitempty"`
	// A fixed value
	Amount AllOfFeeAmount `json:"amount,omitempty"`
}
