/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type Ratingpropertiesvalue string

// The agent that is currently handling the fulfillment of the order
type AllOfFulfillmentAgent struct {
	Person Person `json:"person,omitempty"`

	Contact Contact `json:"contact,omitempty"`

	Organization Organization `json:"organization,omitempty"`

	Rating Ratingpropertiesvalue `json:"rating,omitempty"`
}
