/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a city
type City struct {
	// Name of the city
	Name string `json:"name,omitempty"`
	// City code
	Code string `json:"code,omitempty"`
}
