/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Details of the item that the consumer wants to order
type AllOfIntentItem struct {
	// ID of the item.
	Id string `json:"id,omitempty"`
	// ID of the item, this item is a variant of
	ParentItemId string `json:"parent_item_id,omitempty"`
	// The number of units of the parent item this item is a multiple of
	ParentItemQuantity string `json:"parent_item_quantity,omitempty"`
	// Physical description of the item
	Descriptor string `json:"descriptor,omitempty"`
	// The creator of this item
	Creator string `json:"creator,omitempty"`
	// The price of this item, if it has intrinsic value
	Price string `json:"price,omitempty"`
	// The selling quantity of the item
	Quantity string `json:"quantity,omitempty"`
	// Categories this item can be listed under
	CategoryIds []string `json:"category_ids,omitempty"`
	// Modes through which this item can be fulfilled
	FulfillmentIds []string `json:"fulfillment_ids,omitempty"`
	// Provider Locations this item is available in
	LocationIds []string `json:"location_ids,omitempty"`
	// Payment modalities through which this item can be ordered
	PaymentIds []string `json:"payment_ids,omitempty"`

	AddOns []AddOn `json:"add_ons,omitempty"`
	// Cancellation terms of this item
	CancellationTerms []CancellationTerm `json:"cancellation_terms,omitempty"`
	// Refund terms of this item
	RefundTerms []ItemRefundTerms `json:"refund_terms,omitempty"`
	// Terms that are applicable be met when this item is replaced
	ReplacementTerms []ReplacementTerm `json:"replacement_terms,omitempty"`
	// Terms that are applicable when this item is returned
	ReturnTerms []ReturnTerm `json:"return_terms,omitempty"`
	// Additional input required from the customer to purchase / avail this item
	Xinput string `json:"xinput,omitempty"`
	// Temporal attributes of this item. This property is used when the item exists on the catalog only for a limited period of time.
	Time string `json:"time,omitempty"`
	// Whether this item can be rated
	Rateable bool `json:"rateable,omitempty"`
	// The rating of the item
	Rating string `json:"rating,omitempty"`
	// Whether this item is an exact match of the request
	Matched bool `json:"matched,omitempty"`
	// Whether this item is a related item to the exactly matched item
	Related bool `json:"related,omitempty"`
	// Whether this item is a recommended item to a response
	Recommended bool `json:"recommended,omitempty"`
	// Time to live in seconds for an instance of this schema
	Ttl string `json:"ttl,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}
