/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

import (
	"time"
)

// Describes time in its various forms. It can be a single point in time; duration; or a structured timetable of operations<br>This has properties like label, time stamp,duration,range, days, schedule
type Time struct {
	Label string `json:"label,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`

	Duration string `json:"duration,omitempty"`

	Range_ TimeRange `json:"range,omitempty"`
	// comma separated values representing days of the week
	Days string `json:"days,omitempty"`

	Schedule Schedule `json:"schedule,omitempty"`
}
