/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Details of customer support
type Support struct {
	RefId string `json:"ref_id,omitempty"`

	CallbackPhone string `json:"callback_phone,omitempty"`

	Phone string `json:"phone,omitempty"`

	Email string `json:"email,omitempty"`

	Url string `json:"url,omitempty"`
}
