/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a language known to the person.
type PersonLanguages struct {
	Code string `json:"code,omitempty"`

	Name string `json:"name,omitempty"`
}
