/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Describes a circular region of a specified radius centered at a specified GPS coordinate.
type Circle struct {
	Gps string `json:"gps,omitempty"`

	Radius Scalar `json:"radius,omitempty"`
}
