/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// The location where the transaction is intended to be fulfilled.
type AllOfContextLocation struct {
	Id string `json:"id,omitempty"`

	Descriptor *Descriptor `json:"descriptor,omitempty"`
	// The url to the map of the location. This can be a globally recognized map url or the one specified by the network policy.
	MapUrl string `json:"map_url,omitempty"`
	// The GPS co-ordinates of this location.
	Gps string `json:"gps,omitempty"`
	// The address of this location.
	Address string `json:"address,omitempty"`
	// The city this location is, or is located within
	City string `json:"city,omitempty"`
	// The state this location is, or is located within
	District string `json:"district,omitempty"`
	// The state this location is, or is located within
	State string `json:"state,omitempty"`
	// The country this location is, or is located within
	Country string `json:"country,omitempty"`

	AreaCode string `json:"area_code,omitempty"`

	Circle *Circle `json:"circle,omitempty"`
	// The boundary polygon of this location
	Polygon string `json:"polygon,omitempty"`
	// The three dimensional region describing this location
	Var3dspace string `json:"3dspace,omitempty"`
	// The rating of this location
	Rating string `json:"rating,omitempty"`
}
