/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Subscriber URL of the BAP for accepting callbacks from BPPs.
type AllOfContextBapUri struct {
}
