/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

import (
	"time"
)

// Describes a cancellation event
type Cancellation struct {
	// Date-time when the order was cancelled by the buyer
	Time time.Time `json:"time,omitempty"`

	CancelledBy string `json:"cancelled_by,omitempty"`
	// The reason for cancellation
	Reason *AllOfCancellationReason `json:"reason,omitempty"`
	// Any additional information regarding the nature of cancellation
	AdditionalDescription *AllOfCancellationAdditionalDescription `json:"additional_description,omitempty"`
}
