/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// The selling quantity of the item
type AllOfItemQuantity struct {
	Allocated Quantity `json:"allocated,omitempty"`

	Available Quantity `json:"available,omitempty"`

	Maximum Quantity `json:"maximum,omitempty"`

	Minimum Quantity `json:"minimum,omitempty"`

	Selected Quantity `json:"selected,omitempty"`

	Unitized Quantity `json:"unitized,omitempty"`
}
