/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type SizeTypeEnum string

const (
	xS     SizeTypeEnum = "xs"
	sM     SizeTypeEnum = "sm"
	mD     SizeTypeEnum = "sm"
	lG     SizeTypeEnum = "lg"
	xL     SizeTypeEnum = "xl"
	custom SizeTypeEnum = "custom"
)

// Describes an image
type Image struct {
	// URL to the image. This can be a data url or an remote url
	Url string `json:"url,omitempty"`
	// The size of the image. The network policy can define the default dimensions of each type
	SizeType SizeTypeEnum `json:"size_type,omitempty"`
	// Width of the image in pixels
	Width string `json:"width,omitempty"`
	// Height of the image in pixels
	Height string `json:"height,omitempty"`
}
