/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

type AllOfItemParentItemId string
type AllOfItemCategoryIdsItems string
type AllOfItemFulfillmentIdsItems string
type AllOfItemLocationIdsItems string
type AllOfItemPaymentIdsItems string
type AllOfItemRating string

// Describes a product or a service offered to the end consumer by the provider. In the mobility sector, it can represent a fare product like one way journey. In the logistics sector, it can represent the delivery service offering. In the retail domain it can represent a product like a grocery item.
type Item struct {
	// ID of the item.
	Id string `json:"id,omitempty"`
	// ID of the item, this item is a variant of
	ParentItemId AllOfItemParentItemId `json:"parent_item_id,omitempty"`
	// The number of units of the parent item this item is a multiple of
	ParentItemQuantity AllOfItemParentItemQuantity `json:"parent_item_quantity,omitempty"`
	// Physical description of the item
	Descriptor AllOfItemDescriptor `json:"descriptor,omitempty"`
	// The creator of this item
	Creator AllOfItemCreator `json:"creator,omitempty"`
	// The price of this item, if it has intrinsic value
	Price AllOfItemPrice `json:"price,omitempty"`
	// The selling quantity of the item
	Quantity AllOfItemQuantity `json:"quantity,omitempty"`
	// Categories this item can be listed under
	CategoryIds []AllOfItemCategoryIdsItems `json:"category_ids,omitempty"`
	// Modes through which this item can be fulfilled
	FulfillmentIds []AllOfItemFulfillmentIdsItems `json:"fulfillment_ids,omitempty"`
	// Provider Locations this item is available in
	LocationIds []AllOfItemLocationIdsItems `json:"location_ids,omitempty"`
	// Payment modalities through which this item can be ordered
	PaymentIds []AllOfItemPaymentIdsItems `json:"payment_ids,omitempty"`

	AddOns []AddOn `json:"add_ons,omitempty"`
	// Cancellation terms of this item
	CancellationTerms []CancellationTerm `json:"cancellation_terms,omitempty"`
	// Refund terms of this item
	RefundTerms []ItemRefundTerms `json:"refund_terms,omitempty"`
	// Terms that are applicable be met when this item is replaced
	ReplacementTerms []ReplacementTerm `json:"replacement_terms,omitempty"`
	// Terms that are applicable when this item is returned
	ReturnTerms []ReturnTerm `json:"return_terms,omitempty"`
	// Additional input required from the customer to purchase / avail this item
	Xinput AllOfItemXinput `json:"xinput,omitempty"`
	// Temporal attributes of this item. This property is used when the item exists on the catalog only for a limited period of time.
	Time AllOfItemTime `json:"time,omitempty"`
	// Whether this item can be rated
	Rateable bool `json:"rateable,omitempty"`
	// The rating of the item
	Rating AllOfItemRating `json:"rating,omitempty"`
	// Whether this item is an exact match of the request
	Matched bool `json:"matched,omitempty"`
	// Whether this item is a related item to the exactly matched item
	Related bool `json:"related,omitempty"`
	// Whether this item is a recommended item to a response
	Recommended bool `json:"recommended,omitempty"`
	// Time to live in seconds for an instance of this schema
	Ttl string `json:"ttl,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}
