/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package types

// Details on how the customer wants to pay for the order
type AllOfIntentPayment struct {
	// ID of the payment term that can be referred at an item or an order level in a catalog
	Id string `json:"id,omitempty"`
	// This field indicates who is the collector of payment. The BAP can set this value to 'bap' if it wants to collect the payment first and  settle it to the BPP. If the BPP agrees to those terms, the BPP should not send the payment url. Alternatively, the BPP can set this field with the value 'bpp' if it wants the payment to be made directly.
	CollectedBy string `json:"collected_by,omitempty"`
	// A payment url to be called by the BAP. If empty, then the payment is to be done offline. The details of payment should be present in the params object. If tl_method = http/get, then the payment details will be sent as url params. Two url param values, ```$transaction_id``` and ```$amount``` are mandatory.
	Url string `json:"url,omitempty"`

	Params PaymentParams `json:"params,omitempty"`

	Type_ string `json:"type,omitempty"`

	Status string `json:"status,omitempty"`

	Time Time `json:"time,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}
